package com.ozplugins.AutoUtilitySpell;

public enum AutoUtilitySpellState
{
	TIMEOUT,
	FIND_BANK,
	ANIMATING,
	UNHANDLED_STATE,
	HANDLE_TELEPORT,
	HANDLE_ALCH,
	HANDLE_SPIN_FLAX,
	HANDLE_TAN_LEATHER,
	HANDLE_STRING_JEWELRY,
	HANDLE_HUNTER_KIT,
	HANDLE_PLANK_MAKE,
	BANK_PIN,
	MOVING,
	IDLE;
}
